// apps/web/app/components/Documentation.tsx
import { CodeBlock } from "./CodeBlock";
import { InstallTabs } from "./InstallTabs";

const METHODS = [
  { name: "loadImage(url)", desc: "Load image from URL" },
  { name: "loadGradient(colors, angle?)", desc: "Load gradient as source" },
  { name: "loadBlob(blob)", desc: "Load from Blob or File" },
  { name: "start()", desc: "Start animation" },
  { name: "stop()", desc: "Stop animation" },
  { name: "resize()", desc: "Update dimensions" },
  { name: "dispose()", desc: "Clean up resources" },
];

const OPTIONS = [
  {
    name: "warpIntensity",
    type: "number",
    default: "1.0",
    desc: "Warp effect strength (0-1)",
  },
  {
    name: "blurPasses",
    type: "number",
    default: "8",
    desc: "Kawase blur passes (1-40)",
  },
  {
    name: "animationSpeed",
    type: "number",
    default: "1.0",
    desc: "Animation speed multiplier",
  },
  {
    name: "transitionDuration",
    type: "number",
    default: "1000",
    desc: "Crossfade duration in ms",
  },
  {
    name: "saturation",
    type: "number",
    default: "1.5",
    desc: "Color saturation multiplier",
  },
  {
    name: "tintColor",
    type: "[r, g, b]",
    default: "[0.16, 0.16, 0.24]",
    desc: "Tint color for dark areas (0-1)",
  },
  {
    name: "tintIntensity",
    type: "number",
    default: "0.15",
    desc: "Tint effect strength (0-1)",
  },
  {
    name: "dithering",
    type: "number",
    default: "0.008",
    desc: "Dithering strength (0-0.1)",
  },
];

const QUICK_START_CODE = `import { Kawarp } from '@kawarp/core';

const canvas = document.querySelector('canvas');
const kawarp = new Kawarp(canvas);

await kawarp.loadImage('path/to/image.jpg');
kawarp.start();`;

const REACT_BASIC_CODE = `import { Kawarp } from '@kawarp/react';

function App() {
  return (
    <Kawarp
      src="/image.jpg"
      warpIntensity={0.8}
      style={{ width: '100%', height: '100vh' }}
    />
  );
}`;

const REACT_HOOK_CODE = `import { Kawarp, useKawarp } from '@kawarp/react';

function App() {
  const { ref, loadImage, loadBlob } = useKawarp();

  const handleUpload = async (file: File) => {
    await loadBlob(file);
  };

  return (
    <>
      <Kawarp ref={ref} src="/initial.jpg" />
      <button onClick={() => loadImage('/new.jpg')}>
        Load New Image
      </button>
    </>
  );
}`;

const REACT_PROPS = [
  { name: "src", type: "string", desc: "Image URL (auto-loads on change)" },
  {
    name: "autoPlay",
    type: "boolean",
    default: "true",
    desc: "Auto-start animation",
  },
  { name: "onLoad", type: "() => void", desc: "Called when image loads" },
  { name: "onError", type: "(error) => void", desc: "Called on load error" },
  { name: "className", type: "string", desc: "Container class name" },
  { name: "style", type: "CSSProperties", desc: "Container styles" },
];

function OptionsTable({
  options,
}: {
  options: Array<{
    name: string;
    type: string;
    default?: string;
    desc: string;
  }>;
}) {
  return (
    <div className="overflow-hidden rounded-xl border border-white/10">
      <table className="w-full text-left text-sm">
        <thead className="border-b border-white/10 bg-white/5">
          <tr>
            <th className="px-4 py-3 font-medium text-zinc-300">Option</th>
            <th className="px-4 py-3 font-medium text-zinc-300">Type</th>
            <th className="px-4 py-3 font-medium text-zinc-300">Default</th>
            <th className="px-4 py-3 font-medium text-zinc-300">Description</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-white/5">
          {options.map((option) => (
            <tr key={option.name}>
              <td className="px-4 py-3 font-mono text-xs text-zinc-400">
                {option.name}
              </td>
              <td className="px-4 py-3 text-zinc-500">{option.type}</td>
              <td className="px-4 py-3 text-zinc-500">
                {option.default ?? "-"}
              </td>
              <td className="px-4 py-3 text-zinc-400">{option.desc}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export function Documentation() {
  return (
    <section className="relative z-10 border-t border-white/10 bg-zinc-950/90 backdrop-blur-xl">
      <div className="mx-auto max-w-3xl px-6 py-16 md:py-24">
        <h2 className="mb-6 text-3xl font-semibold tracking-tight text-white">
          Documentation
        </h2>

        <p className="mb-12 text-zinc-400 leading-relaxed">
          Kawarp is a WebGL-powered library for creating fluid, animated
          background effects similar to Apple Music&apos;s album art
          visualization. It uses Kawase blur for efficient, high-quality
          blurring and simplex noise-based domain warping for organic motion.
          The library is optimized for performance with blur operations running
          on small textures only when the image changes, while per-frame
          rendering is minimal.
        </p>

        <div className="space-y-12">
          <div>
            <h3 className="mb-4 text-lg font-medium text-white">
              Installation
            </h3>
            <InstallTabs />
          </div>

          <div>
            <h3 className="mb-4 text-lg font-medium text-white">Quick Start</h3>
            <CodeBlock code={QUICK_START_CODE} />
          </div>

          <div>
            <h3 className="mb-4 text-lg font-medium text-white">Options</h3>
            <OptionsTable options={OPTIONS} />
          </div>

          <div>
            <h3 className="mb-4 text-lg font-medium text-white">Methods</h3>
            <div className="space-y-3">
              {METHODS.map((method) => (
                <div
                  key={method.name}
                  className="flex items-center gap-4 rounded-lg border border-white/10 bg-white/5 px-4 py-3"
                >
                  <code className="shrink-0 font-mono text-sm text-zinc-300">
                    {method.name}
                  </code>
                  <span className="text-sm text-zinc-500">{method.desc}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="border-t border-white/10 pt-12">
            <h2 className="mb-8 text-2xl font-semibold tracking-tight text-white">
              React
            </h2>

            <div className="space-y-12">
              <div>
                <h3 className="mb-4 text-lg font-medium text-white">
                  Installation
                </h3>
                <InstallTabs packageName="@kawarp/react" />
              </div>

              <div>
                <h3 className="mb-4 text-lg font-medium text-white">
                  Basic Usage
                </h3>
                <CodeBlock code={REACT_BASIC_CODE} />
              </div>

              <div>
                <h3 className="mb-4 text-lg font-medium text-white">
                  useKawarp Hook
                </h3>
                <p className="mb-4 text-sm text-zinc-400">
                  For operations that can&apos;t be done via props—like loading
                  from files, blobs, or gradients—use the useKawarp hook.
                </p>
                <CodeBlock code={REACT_HOOK_CODE} />
              </div>

              <div>
                <h3 className="mb-4 text-lg font-medium text-white">
                  Component Props
                </h3>
                <p className="mb-4 text-sm text-zinc-400">
                  All core options are available as props, plus React-specific
                  ones:
                </p>
                <OptionsTable options={REACT_PROPS} />
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

// apps/angular-app/src/app/components/documentation.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { METHODS, OPTIONS, QUICK_START_CODE, ANGULAR_BASIC_CODE, ANGULAR_IMPERATIVE_CODE, REACT_PROPS } from '../constants';
import { CodeBlockComponent } from './code-block.component';
import { InstallTabsComponent } from './install-tabs.component';

@Component({
  selector: 'app-documentation',
  standalone: true,
  imports: [CodeBlockComponent, InstallTabsComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="relative z-10 border-t border-white/10 bg-zinc-950/90 backdrop-blur-xl">
      <div class="mx-auto max-w-3xl px-6 py-16 md:py-24">
        <h2 class="mb-6 text-3xl font-semibold tracking-tight text-white">Documentation</h2>

        <p class="mb-12 text-zinc-400 leading-relaxed">
          Kawarp is a zero-dependency, WebGL-powered library for creating fluid,
          animated background effects similar to Apple Music's album art
          visualization. It uses Kawase blur for efficient, high-quality
          blurring and simplex noise-based domain warping for organic motion.
          The library is optimized for performance with blur operations running
          on small textures only when the image changes, while per-frame
          rendering is minimal.
        </p>

        <div class="flex flex-col gap-12">
          <!-- Installation -->
          <div>
            <h3 class="mb-4 text-lg font-medium text-white">Installation</h3>
            <app-install-tabs />
          </div>

          <!-- Quick Start -->
          <div>
            <h3 class="mb-4 text-lg font-medium text-white">Quick Start</h3>
            <app-code-block [code]="quickStartCode" />
          </div>

          <!-- Options -->
          <div>
            <h3 class="mb-4 text-lg font-medium text-white">Options</h3>
            <div class="overflow-hidden rounded-xl border border-white/10">
              <table class="w-full text-left text-sm border-collapse">
                <thead class="border-b border-white/10 bg-white/5">
                  <tr>
                    <th class="px-4 py-3 font-medium text-zinc-300">Option</th>
                    <th class="px-4 py-3 font-medium text-zinc-300">Type</th>
                    <th class="px-4 py-3 font-medium text-zinc-300">Default</th>
                    <th class="px-4 py-3 font-medium text-zinc-300">Description</th>
                  </tr>
                </thead>
                <tbody class="divide-y divide-white/5">
                  @for (opt of options; track opt.name) {
                    <tr>
                      <td class="px-4 py-3 font-mono text-xs text-zinc-400">{{ opt.name }}</td>
                      <td class="px-4 py-3 text-zinc-500">{{ opt.type }}</td>
                      <td class="px-4 py-3 text-zinc-500">{{ $any(opt).default ?? '-' }}</td>
                      <td class="px-4 py-3 text-zinc-400">{{ opt.desc }}</td>
                    </tr>
                  }
                </tbody>
              </table>
            </div>
          </div>

          <!-- Methods -->
          <div>
            <h3 class="mb-4 text-lg font-medium text-white">Methods</h3>
            <div class="flex flex-col gap-3">
              @for (method of methods; track method.name) {
                <div class="flex items-center gap-4 rounded-lg border border-white/10 bg-white/5 px-4 py-3">
                  <code class="shrink-0 font-mono text-sm text-zinc-300">{{ method.name }}</code>
                  <span class="text-sm text-zinc-500">{{ method.desc }}</span>
                </div>
              }
            </div>
          </div>

          <!-- Angular Section -->
          <div class="pt-12 border-t border-white/10">
            <h2 class="mb-8 text-2xl font-semibold tracking-tight text-white">Angular</h2>

            <div class="flex flex-col gap-12">
              <div>
                <h3 class="mb-4 text-lg font-medium text-white">Installation</h3>
                <app-install-tabs packageName="@kawarp/angular" />
              </div>

              <div>
                <h3 class="mb-4 text-lg font-medium text-white">Basic Usage</h3>
                <app-code-block [code]="angularBasicCode" />
              </div>

              <div>
                <h3 class="mb-4 text-lg font-medium text-white">Imperative API</h3>
                <p class="mb-4 text-sm text-zinc-400">
                  For operations that can't be done via inputs—like loading
                  from files, blobs, or gradients—use the component instance methods.
                </p>
                <app-code-block [code]="angularImperativeCode" />
              </div>

              <div>
                <h3 class="mb-4 text-lg font-medium text-white">Component Inputs</h3>
                <p class="mb-4 text-sm text-zinc-400">
                  All core options are available as inputs, plus Angular-specific ones:
                </p>
                <div class="overflow-hidden rounded-xl border border-white/10">
                  <table class="w-full text-left text-sm border-collapse">
                    <thead class="border-b border-white/10 bg-white/5">
                      <tr>
                        <th class="px-4 py-3 font-medium text-zinc-300">Input</th>
                        <th class="px-4 py-3 font-medium text-zinc-300">Type</th>
                        <th class="px-4 py-3 font-medium text-zinc-300">Default</th>
                        <th class="px-4 py-3 font-medium text-zinc-300">Description</th>
                      </tr>
                    </thead>
                    <tbody class="divide-y divide-white/5">
                      @for (prop of reactProps; track prop.name) {
                        <tr>
                          <td class="px-4 py-3 font-mono text-xs text-zinc-400">{{ prop.name }}</td>
                          <td class="px-4 py-3 text-zinc-500">{{ prop.type }}</td>
                          <td class="px-4 py-3 text-zinc-500">{{ $any(prop).default ?? '-' }}</td>
                          <td class="px-4 py-3 text-zinc-400">{{ prop.desc }}</td>
                        </tr>
                      }
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  `,
})
export class DocumentationComponent {
  readonly options = OPTIONS;
  readonly methods = METHODS;
  readonly quickStartCode = QUICK_START_CODE;
  readonly angularBasicCode = ANGULAR_BASIC_CODE;
  readonly angularImperativeCode = ANGULAR_IMPERATIVE_CODE;
  readonly reactProps = REACT_PROPS;
}
