// apps/web/app/components/Slider.tsx
"use client";

interface SliderProps {
  min: number;
  max: number;
  step: number;
  value: number;
  onChange: (value: number) => void;
}

export function Slider({ min, max, step, value, onChange }: SliderProps) {
  const percent = ((value - min) / (max - min)) * 100;

  return (
    <div className="slider-container">
      <div className="slider-track">
        <div className="slider-progress" style={{ width: `${percent}%` }} />
      </div>
      <div className="slider-thumb" style={{ left: `${percent}%` }} />
      <input
        type="range"
        min={min}
        max={max}
        step={step}
        value={value}
        onChange={(e) => onChange(Number(e.target.value))}
      />
    </div>
  );
}

// apps/angular-app/src/app/components/slider.component.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';

@Component({
  selector: 'app-slider',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="slider-container">
      <div class="slider-track">
        <div class="slider-progress" [style.width.%]="percent()"></div>
      </div>
      <div class="slider-thumb" [style.left.%]="percent()"></div>
      <input
        type="range"
        [min]="min()"
        [max]="max()"
        [step]="step()"
        [value]="value()"
        (input)="onChange($event)"
      />
    </div>
  `,
})
export class SliderComponent {
  readonly min = input.required<number>();
  readonly max = input.required<number>();
  readonly step = input.required<number>();
  readonly value = input.required<number>();
  readonly valueChange = output<number>();

  readonly percent = computed(() => ((this.value() - this.min()) / (this.max() - this.min())) * 100);

  onChange = (e: Event) => {
    const target = e.target as HTMLInputElement;
    this.valueChange.emit(Number(target.value));
  };
}
