// apps/angular-app/src/app/components/control-panel.component.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { PRESETS } from '../constants';
import { SliderComponent } from './slider.component';

const rgbToHex = (rgb: [number, number, number]): string =>
  '#' + rgb.map(v => Math.round(v * 255).toString(16).padStart(2, '0')).join('');

const hexToRgb = (hex: string): [number, number, number] => {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result && result[1] && result[2] && result[3]
    ? [parseInt(result[1], 16) / 255, parseInt(result[2], 16) / 255, parseInt(result[3], 16) / 255]
    : [0.157, 0.157, 0.235];
};

@Component({
  selector: 'app-control-panel',
  standalone: true,
  imports: [SliderComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <!-- Backdrop -->
    @if (isOpen()) {
      <div class="fixed inset-0 z-20" (click)="close.emit()"></div>
    }

    <div class="fixed right-6 top-1/2 z-30 flex -translate-y-1/2 items-center gap-3 md:right-8">
      <!-- Panel -->
      @if (isOpen()) {
        <div
          class="w-80 md:w-[480px] max-h-[85vh] overflow-y-auto rounded-2xl border border-white/5 bg-zinc-950/90 p-4 shadow-2xl backdrop-blur-md origin-right animate-fade-in-scale"
          (dragover)="$event.stopPropagation()"
          (dragleave)="$event.stopPropagation()"
          (drop)="$event.stopPropagation()"
        >
          <!-- Presets -->
          <div class="mb-5">
            <span class="mb-3 block text-xs text-zinc-500 font-semibold">Presets</span>
            <div class="grid grid-cols-3 md:grid-cols-6 gap-2">
              @for (preset of presets; track preset.name; let i = $index) {
                <button
                  type="button"
                  class="relative aspect-square overflow-hidden rounded-lg border-2 transition-[transform,border-color] duration-100 hover:scale-105 active:scale-95"
                  [class.border-white]="activePreset() === i"
                  [class.border-transparent]="activePreset() !== i"
                  [title]="preset.name"
                  (click)="presetSelect.emit(i)"
                >
                  <img [src]="preset.url" [alt]="preset.name" class="w-full h-full object-cover select-none pointer-events-none" />
                </button>
              }
            </div>
          </div>

          <!-- Parameters -->
          <div class="border-t border-white/5 py-4">
            <span class="mb-4 block text-xs text-zinc-500 font-semibold">Parameters</span>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <div class="mb-1.5 flex items-center justify-between">
                  <span class="text-xs text-zinc-200">Warp</span>
                  <span class="text-xs tabular-nums text-zinc-500">{{ warpIntensity().toFixed(2) }}</span>
                </div>
                <app-slider [min]="0" [max]="1" [step]="0.01" [value]="warpIntensity()" (valueChange)="warpIntensityChange.emit($event)" />
              </div>
              <div>
                <div class="mb-1.5 flex items-center justify-between">
                  <span class="text-xs text-zinc-200">Blur</span>
                  <span class="text-xs tabular-nums text-zinc-500">{{ blurPasses() }}</span>
                </div>
                <app-slider [min]="1" [max]="40" [step]="1" [value]="blurPasses()" (valueChange)="blurPassesChange.emit($event)" />
              </div>
              <div>
                <div class="mb-1.5 flex items-center justify-between">
                  <span class="text-xs text-zinc-200">Speed</span>
                  <span class="text-xs tabular-nums text-zinc-500">{{ animationSpeed().toFixed(1) }}×</span>
                </div>
                <app-slider [min]="0.1" [max]="3" [step]="0.1" [value]="animationSpeed()" (valueChange)="animationSpeedChange.emit($event)" />
              </div>
              <div>
                <div class="mb-1.5 flex items-center justify-between">
                  <span class="text-xs text-zinc-200">Transition</span>
                  <span class="text-xs tabular-nums text-zinc-500">{{ (transitionDuration() / 1000).toFixed(1) }}s</span>
                </div>
                <app-slider [min]="0" [max]="3000" [step]="100" [value]="transitionDuration()" (valueChange)="transitionDurationChange.emit($event)" />
              </div>
              <div>
                <div class="mb-1.5 flex items-center justify-between">
                  <span class="text-xs text-zinc-200">Saturation</span>
                  <span class="text-xs tabular-nums text-zinc-500">{{ saturation().toFixed(2) }}</span>
                </div>
                <app-slider [min]="0" [max]="3" [step]="0.05" [value]="saturation()" (valueChange)="saturationChange.emit($event)" />
              </div>
              <div>
                <div class="mb-1.5 flex items-center justify-between">
                  <span class="text-xs text-zinc-200">Tint</span>
                  <div class="flex items-center gap-2">
                    <label class="block h-4 w-4 cursor-pointer rounded-full border border-white/20" [style.background-color]="tintColorHex()">
                      <input type="color" [value]="tintColorHex()" (input)="onTintColorChange($event)" class="sr-only" />
                    </label>
                    <span class="text-xs tabular-nums text-zinc-500">{{ (tintIntensity() * 100).toFixed(0) }}%</span>
                  </div>
                </div>
                <app-slider [min]="0" [max]="1" [step]="0.01" [value]="tintIntensity()" (valueChange)="tintIntensityChange.emit($event)" />
              </div>
              <div>
                <div class="mb-1.5 flex items-center justify-between">
                  <span class="text-xs text-zinc-200">Dither</span>
                  <span class="text-xs tabular-nums text-zinc-500">{{ (dithering() * 1000).toFixed(1) }}</span>
                </div>
                <app-slider [min]="0" [max]="0.1" [step]="0.001" [value]="dithering()" (valueChange)="ditheringChange.emit($event)" />
              </div>
              <div>
                <div class="mb-1.5 flex items-center justify-between">
                  <span class="text-xs text-zinc-200">Scale</span>
                  <span class="text-xs tabular-nums text-zinc-500">{{ scale().toFixed(2) }}</span>
                </div>
                <app-slider [min]="0.01" [max]="4" [step]="0.01" [value]="scale()" (valueChange)="scaleChange.emit($event)" />
              </div>
            </div>
          </div>

          <!-- Custom image -->
          <div class="border-t border-white/5 pt-4">
            <span class="mb-3 block text-xs text-zinc-500 font-semibold">Custom image</span>
            <div class="flex gap-2">
              <input
                type="text"
                class="flex-1 rounded-lg border border-white/10 px-3 py-2 text-sm text-zinc-200 placeholder-zinc-500 outline-none transition-colors focus:border-white/20 bg-transparent"
                placeholder="Image URL..."
                [value]="imageUrl()"
                (input)="onImageUrlInput($event)"
                (keydown.enter)="loadFromUrl.emit()"
              />
              <button
                type="button"
                class="rounded-lg bg-white/10 px-3 py-2 text-sm text-zinc-200 transition-colors hover:bg-white/20"
                (click)="loadFromUrl.emit()"
              >
                Go
              </button>
            </div>
            <div class="mt-2 flex gap-2">
              <button
                type="button"
                class="flex-1 rounded-lg border border-white/20 py-2 text-xs text-zinc-400 transition-colors hover:border-white/40 hover:text-zinc-200 bg-transparent"
                (click)="fileInput.click()"
              >
                Upload
              </button>
              <input
                #fileInput
                type="file"
                accept="image/*"
                class="hidden"
                (change)="onFileChange($event)"
              />
              <div class="flex items-center justify-center rounded-lg border border-white/20 py-2 px-2 text-xs text-zinc-300 opacity-50 select-none">
                ⌘V paste
              </div>
            </div>
          </div>
        </div>
      }

      <!-- Toggle button -->
      <button
        type="button"
        class="rounded-full bg-white/10 p-3 text-white backdrop-blur-md transition-colors hover:bg-white/20"
        (click)="toggle.emit()"
      >
        @if (isOpen()) {
          <svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M6 18L18 6M6 6l12 12" />
          </svg>
        } @else {
          <svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M10.5 6h9.75M10.5 6a1.5 1.5 0 11-3 0m3 0a1.5 1.5 0 10-3 0M3.75 6H7.5m3 12h9.75m-9.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-3.75 0H7.5m9-6h3.75m-3.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-9.75 0h9.75" />
          </svg>
        }
      </button>
    </div>
  `,
})
export class ControlPanelComponent {
  readonly presets = PRESETS;

  // Inputs
  readonly isOpen = input.required<boolean>();
  readonly activePreset = input.required<number>();
  readonly imageUrl = input.required<string>();
  readonly warpIntensity = input.required<number>();
  readonly blurPasses = input.required<number>();
  readonly animationSpeed = input.required<number>();
  readonly transitionDuration = input.required<number>();
  readonly saturation = input.required<number>();
  readonly tintColor = input.required<[number, number, number]>();
  readonly tintIntensity = input.required<number>();
  readonly dithering = input.required<number>();
  readonly scale = input.required<number>();

  // Outputs
  readonly toggle = output<void>();
  readonly close = output<void>();
  readonly presetSelect = output<number>();
  readonly imageUrlChange = output<string>();
  readonly loadFromUrl = output<void>();
  readonly fileSelect = output<File>();
  readonly warpIntensityChange = output<number>();
  readonly blurPassesChange = output<number>();
  readonly animationSpeedChange = output<number>();
  readonly transitionDurationChange = output<number>();
  readonly saturationChange = output<number>();
  readonly tintColorChange = output<[number, number, number]>();
  readonly tintIntensityChange = output<number>();
  readonly ditheringChange = output<number>();
  readonly scaleChange = output<number>();

  readonly tintColorHex = computed(() => rgbToHex(this.tintColor()));

  onTintColorChange = (e: Event) => {
    const target = e.target as HTMLInputElement;
    this.tintColorChange.emit(hexToRgb(target.value));
  };

  onImageUrlInput = (e: Event) => {
    const target = e.target as HTMLInputElement;
    this.imageUrlChange.emit(target.value);
  };

  onFileChange = (e: Event) => {
    const target = e.target as HTMLInputElement;
    const file = target.files?.[0];
    if (file) this.fileSelect.emit(file);
  };
}

// apps/web/app/components/ControlPanel.tsx
"use client";

import { AnimatePresence, motion } from "motion/react";
import Image from "next/image";
import { useRef } from "react";
import { PRESETS } from "../constants";
import { Slider } from "./Slider";

interface ControlPanelProps {
  isOpen: boolean;
  onToggle: () => void;
  onClose: () => void;
  activePreset: number;
  onPresetSelect: (index: number) => void;
  imageUrl: string;
  onImageUrlChange: (url: string) => void;
  onLoadFromUrl: () => void;
  onFileSelect: (file: File) => void;
  warpIntensity: number;
  onWarpIntensityChange: (value: number) => void;
  blurPasses: number;
  onBlurPassesChange: (value: number) => void;
  animationSpeed: number;
  onAnimationSpeedChange: (value: number) => void;
  transitionDuration: number;
  onTransitionDurationChange: (value: number) => void;
  saturation: number;
  onSaturationChange: (value: number) => void;
  tintColor: [number, number, number];
  onTintColorChange: (value: [number, number, number]) => void;
  tintIntensity: number;
  onTintIntensityChange: (value: number) => void;
  dithering: number;
  onDitheringChange: (value: number) => void;
  scale: number;
  onScaleChange: (value: number) => void;
}

function rgbToHex(rgb: [number, number, number]): string {
  return (
    "#" +
    rgb
      .map((v) =>
        Math.round(v * 255)
          .toString(16)
          .padStart(2, "0"),
      )
      .join("")
  );
}

function hexToRgb(hex: string): [number, number, number] {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  if (!result || !result[1] || !result[2] || !result[3]) {
    return [0.157, 0.157, 0.235];
  }
  return [
    parseInt(result[1], 16) / 255,
    parseInt(result[2], 16) / 255,
    parseInt(result[3], 16) / 255,
  ];
}

export function ControlPanel({
  isOpen,
  onToggle,
  onClose,
  activePreset,
  onPresetSelect,
  imageUrl,
  onImageUrlChange,
  onLoadFromUrl,
  onFileSelect,
  warpIntensity,
  onWarpIntensityChange,
  blurPasses,
  onBlurPassesChange,
  animationSpeed,
  onAnimationSpeedChange,
  transitionDuration,
  onTransitionDurationChange,
  saturation,
  onSaturationChange,
  tintColor,
  onTintColorChange,
  tintIntensity,
  onTintIntensityChange,
  dithering,
  onDitheringChange,
  scale,
  onScaleChange,
}: ControlPanelProps) {
  const fileInputRef = useRef<HTMLInputElement>(null);

  return (
    <>
      <AnimatePresence>
        {isOpen && (
          <motion.div
            key="backdrop"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.1 }}
            className="fixed inset-0 z-20"
            onClick={onClose}
          />
        )}
      </AnimatePresence>
      <div className="fixed right-6 top-1/2 z-30 flex -translate-y-1/2 items-center gap-3 md:right-8">
        <AnimatePresence>
          {isOpen && (
            <motion.div
              key="panel"
              initial={{ opacity: 0, x: 8, filter: "blur(8px)", scale: 0.95 }}
              animate={{ opacity: 1, x: 0, filter: "blur(0px)", scale: 1 }}
              exit={{ opacity: 0, x: 8, filter: "blur(8px)", scale: 0.95 }}
              transition={{ duration: 0.15 }}
              className="w-80 md:w-[480px] max-h-[85vh] overflow-y-auto rounded-2xl border border-white/5 bg-zinc-950/90 p-4 shadow-2xl backdrop-blur-md origin-right"
              onDragOver={(e) => e.stopPropagation()}
              onDragLeave={(e) => e.stopPropagation()}
              onDrop={(e) => e.stopPropagation()}
            >
              <div className="mb-5">
                <span className="mb-3 block text-xs text-zinc-500 font-semibold">
                  Presets
                </span>
                <div className="grid grid-cols-3 md:grid-cols-6 gap-2">
                  {PRESETS.map((preset, i) => (
                    <motion.button
                      key={preset.name}
                      type="button"
                      onClick={() => onPresetSelect(i)}
                      whileHover={{ scale: 1.05 }}
                      whileTap={{ scale: 0.95 }}
                      className={`relative aspect-square overflow-hidden rounded-lg border-2 ${
                        activePreset === i
                          ? "border-white"
                          : "border-transparent"
                      }`}
                      title={preset.name}
                    >
                      <Image
                        src={preset.url}
                        alt={preset.name}
                        fill
                        className="select-none object-cover"
                        draggable={false}
                      />
                    </motion.button>
                  ))}
                </div>
              </div>

              <div className="border-t border-white/5 py-4">
                <span className="mb-4 block text-xs text-zinc-500 font-semibold">
                  Parameters
                </span>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <div className="mb-1.5 flex items-center justify-between">
                      <span className="text-xs text-zinc-200">Warp</span>
                      <span className="text-xs tabular-nums text-zinc-500">
                        {warpIntensity?.toFixed(2)}
                      </span>
                    </div>
                    <Slider
                      min={0}
                      max={1}
                      step={0.01}
                      value={warpIntensity}
                      onChange={onWarpIntensityChange}
                    />
                  </div>
                  <div>
                    <div className="mb-1.5 flex items-center justify-between">
                      <span className="text-xs text-zinc-200">Blur</span>
                      <span className="text-xs tabular-nums text-zinc-500">
                        {blurPasses}
                      </span>
                    </div>
                    <Slider
                      min={1}
                      max={40}
                      step={1}
                      value={blurPasses}
                      onChange={onBlurPassesChange}
                    />
                  </div>
                  <div>
                    <div className="mb-1.5 flex items-center justify-between">
                      <span className="text-xs text-zinc-200">Speed</span>
                      <span className="text-xs tabular-nums text-zinc-500">
                        {animationSpeed.toFixed(1)}×
                      </span>
                    </div>
                    <Slider
                      min={0.1}
                      max={3}
                      step={0.1}
                      value={animationSpeed}
                      onChange={onAnimationSpeedChange}
                    />
                  </div>
                  <div>
                    <div className="mb-1.5 flex items-center justify-between">
                      <span className="text-xs text-zinc-200">Transition</span>
                      <span className="text-xs tabular-nums text-zinc-500">
                        {(transitionDuration / 1000).toFixed(1)}s
                      </span>
                    </div>
                    <Slider
                      min={0}
                      max={3000}
                      step={100}
                      value={transitionDuration}
                      onChange={onTransitionDurationChange}
                    />
                  </div>
                  <div>
                    <div className="mb-1.5 flex items-center justify-between">
                      <span className="text-xs text-zinc-200">Saturation</span>
                      <span className="text-xs tabular-nums text-zinc-500">
                        {saturation.toFixed(2)}
                      </span>
                    </div>
                    <Slider
                      min={0}
                      max={3}
                      step={0.05}
                      value={saturation}
                      onChange={onSaturationChange}
                    />
                  </div>
                  <div>
                    <div className="mb-1.5 flex items-center justify-between">
                      <span className="text-xs text-zinc-200">Tint</span>
                      <div className="flex items-center gap-2">
                        <label
                          className="block h-4 w-4 cursor-pointer rounded-full border border-white/20"
                          style={{ backgroundColor: rgbToHex(tintColor) }}
                        >
                          <input
                            type="color"
                            value={rgbToHex(tintColor)}
                            onChange={(e) =>
                              onTintColorChange(hexToRgb(e.target.value))
                            }
                            className="sr-only"
                          />
                        </label>
                        <span className="text-xs tabular-nums text-zinc-500">
                          {(tintIntensity * 100).toFixed(0)}%
                        </span>
                      </div>
                    </div>
                    <Slider
                      min={0}
                      max={1}
                      step={0.01}
                      value={tintIntensity}
                      onChange={onTintIntensityChange}
                    />
                  </div>
                  <div>
                    <div className="mb-1.5 flex items-center justify-between">
                      <span className="text-xs text-zinc-200">Dither</span>
                      <span className="text-xs tabular-nums text-zinc-500">
                        {(dithering * 1000).toFixed(1)}
                      </span>
                    </div>
                    <Slider
                      min={0}
                      max={0.1}
                      step={0.001}
                      value={dithering}
                      onChange={onDitheringChange}
                    />
                  </div>
                  <div>
                    <div className="mb-1.5 flex items-center justify-between">
                      <span className="text-xs text-zinc-200">Scale</span>
                      <span className="text-xs tabular-nums text-zinc-500">
                        {scale.toFixed(2)}
                      </span>
                    </div>
                    <Slider
                      min={0.01}
                      max={4}
                      step={0.01}
                      value={scale}
                      onChange={onScaleChange}
                    />
                  </div>
                </div>
              </div>

              <div className="border-t border-white/5 pt-4">
                <span className="mb-3 block text-xs text-zinc-500 font-semibold">
                  Custom image
                </span>
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={imageUrl}
                    onChange={(e) => onImageUrlChange(e.target.value)}
                    placeholder="Image URL..."
                    className="flex-1 rounded-lg border border-white/10 px-3 py-2 text-sm text-zinc-200 placeholder-zinc-500 outline-none transition-colors focus:border-white/20"
                    onKeyDown={(e) => e.key === "Enter" && onLoadFromUrl()}
                  />
                  <button
                    type="button"
                    onClick={onLoadFromUrl}
                    className="rounded-lg bg-white/10 px-3 py-2 text-sm text-zinc-200 transition-colors hover:bg-white/20"
                  >
                    Go
                  </button>
                </div>
                <div className="mt-2 flex gap-2">
                  <button
                    type="button"
                    onClick={() => fileInputRef.current?.click()}
                    className="flex-1 rounded-lg border border-white/20 py-2 text-xs text-zinc-400 transition-colors hover:border-white/40 hover:text-zinc-200"
                  >
                    Upload
                  </button>
                  <input
                    ref={fileInputRef}
                    type="file"
                    accept="image/*"
                    className="hidden"
                    onChange={(e) => {
                      const file = e.target.files?.[0];
                      if (file) onFileSelect(file);
                    }}
                  />
                  <div className="flex items-center justify-center rounded-lg border border-white/20 py-2 px-2 text-xs text-zinc-300 opacity-50">
                    ⌘V paste
                  </div>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
        <button
          type="button"
          onClick={onToggle}
          className="rounded-full bg-white/10 p-3 text-white backdrop-blur-md transition-colors hover:bg-white/20"
        >
          <AnimatePresence mode="wait" initial={false}>
            {isOpen ? (
              <motion.svg
                key="close"
                initial={{ opacity: 0, scale: 0.75 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.75 }}
                transition={{ duration: 0.15 }}
                className="h-5 w-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={1.5}
                  d="M6 18L18 6M6 6l12 12"
                />
              </motion.svg>
            ) : (
              <motion.svg
                key="open"
                initial={{ opacity: 0, scale: 0.75 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.75 }}
                transition={{ duration: 0.15 }}
                className="h-5 w-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={1.5}
                  d="M10.5 6h9.75M10.5 6a1.5 1.5 0 11-3 0m3 0a1.5 1.5 0 10-3 0M3.75 6H7.5m3 12h9.75m-9.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-3.75 0H7.5m9-6h3.75m-3.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-9.75 0h9.75"
                />
              </motion.svg>
            )}
          </AnimatePresence>
        </button>
      </div>
    </>
  );
}
